### ISSUE TITLE
SuggestionsOverlayComponent cannot be used as an entry component

### ISSUE THREAD

**Issue by wkeizer** [jorritdenbroeder/atmention#13]
On implementation in an Angular project I can't add the SuggestionsOverlayComponent to the entryComponents of my Module. It returns an error:

SuggestionsOverlayComponent cannot be used as an entry component.

**Comment by broederj** [comment]
What are you trying to accomplish with that component? It's an internal component (so not part of the public api), which only creates a DOM element for the overlay and provides a context object to your ng-templates.

The idea is that, from your application, you can provide those ng-templates for customizing how the overlay looks, for example:

https://github.com/jorritdenbroeder/atmention/blob/161885eb92925fde6bc80bc9a1e8db4a3c8d090e/packages/atmention-angular-demo/src/app/app.component.html#L15-L21
